apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: dev-secret-store
  target:
    name: gcp-secrets-from-sm
    creationPolicy: Owner
  data:
  - secretKey: jwt-token
    remoteRef:
      key: jwt-token

  - secretKey: jwt-expired
    remoteRef:
      key: jwt-expired

  - secretKey: postgres-db
    remoteRef:
      key: postgres-db

  - secretKey: postgres-port
    remoteRef:
      key: postgres-port

  - secretKey: postgres-ip
    remoteRef:
      key: postgres-ip

  - secretKey: postgres-admin
    remoteRef:
      key: postgres-admin

  - secretKey: postgres-password
    remoteRef:
      key: postgres-password

  - secretKey: redis-ip
    remoteRef:
      key: redis-ip

  - secretKey: redis-port
    remoteRef:
      key: redis-port

  - secretKey: mongo-db
    remoteRef:
      key: mongo-db

  - secretKey: mongo-url
    remoteRef:
      key: mongo-url

  - secretKey: facebook-cl
    remoteRef:
      key: facebook-cl

  - secretKey: facebook-cl-scr
    remoteRef:
      key: facebook-cl-scr

  - secretKey: google-cl-id
    remoteRef:
      key: google-cl-id

  - secretKey: google-cl-scr
    remoteRef:
      key: google-cl-scr