apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshTime }}          
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}  
  target:
    name: {{ .Values.externalSecrets.targetName }}
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: schedule/config
        property: DB_HOST
    - secretKey: DB_NAME
      remoteRef:
        key: schedule/config
        property: DB_NAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: schedule/config
        property: DB_PASSWORD
    - secretKey: DB_PORT
      remoteRef:
        key: schedule/config
        property: DB_PORT
    - secretKey: DB_USERNAME
      remoteRef:
        key: schedule/config
        property: DB_USERNAME
    - secretKey: FACEBOOK_CLIENT_ID
      remoteRef:
        key: schedule/config
        property: FACEBOOK_CLIENT_ID
    - secretKey: FACEBOOK_CLIENT_SECRET
      remoteRef:
        key: schedule/config
        property: FACEBOOK_CLIENT_SECRET
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: schedule/config
        property: GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: schedule/config
        property: GOOGLE_CLIENT_SECRET
    - secretKey: JWT_EXPIRED
      remoteRef:
        key: schedule/config
        property: JWT_EXPIRED
    - secretKey: JWT_SECRET
      remoteRef:
        key: schedule/config
        property: JWT_SECRET
    - secretKey: MONGO_DATABASE
      remoteRef:
        key: schedule/config
        property: MONGO_DATABASE
    - secretKey: MONGO_SERVER
      remoteRef:
        key: schedule/config
        property: MONGO_SERVER
    - secretKey: REDIS_HOST
      remoteRef:
        key: schedule/config
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: schedule/config
        property: REDIS_PORT