apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
 name: dev-secret-store
spec:
 provider:
     gcpsm:  
       projectID: schedule-405513
       auth:
         workloadIdentity:
           clusterLocation: us-west3-b
           clusterName: cluster-2
           serviceAccountRef:
             name: google-sa