apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
    tier: {{ .Release.Name }}
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: 6379
    targetPort: 6379
  type: {{ .Values.service.type }}
