apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  labels:
    app: {{ .Values.mongo.name }}
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.mongo.name }}
