---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: connect
spec:
  selector:
    matchLabels:
      app: schedule-backend
      tier: backend
      env: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: schedule-backend
        tier: backend
        env: dev
    spec:
      containers:
      - name: schedule-back
        image: mneteli/pink:first
        ports:
          - name: backend-port
            containerPort: 8080         
        env:
            - name: JWT_SECRET
              value: jwttoken
            - name: JWT_EXPIRED
              value: "86400000"
              
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_HOST
                  
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_NAME
                  
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PORT      
                        
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USERNAME
                  
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
              
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
              
            - name: MONGO_DATABASE
              value: schedule_mongo
            - name: MONGO_SERVER
              value: mongo
              
            - name: SMTP_HOST
              value: 9h4m03JQURp7
            - name: SMTP_USERNAME
              value: 9h4m03JQURp7
            - name: SMTP_PASSWORD
              value: 9h4m03JQURp7

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: connect
spec:
  selector:
    app: schedule-backend
    tier: backend
    env: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
...
