---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: schedule
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: schedule
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: bobrja/mynginx:2
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"] 
...