apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: schedule
    tier: postgres
    track: stable
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi