---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule
      tier: postgres
      track: stable
  template:
    metadata:
      labels:
        app: schedule
        tier: postgres
        track: stable
    spec:
      containers:
      - name: postgres
        image: "postgres:15.1-alpine"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: schedule
        - name: POSTGRES_PASSWORD
          value: 9h4m03JQURp7
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: schedule
    tier: postgres
    env: dev
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
...