apiVersion: v1
kind: Secret
metadata:
  name: schedule-secret
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMK
  DB_PORT: NTQzMg==
  DB_NAME: c2NoZWR1bGU=
  DB_USERNAME: c2NoZWR1bGU=
  DB_PASSWORD: cGFzcw==
  JWT_SECRET: and0c2VjcmV0Cg==
  JWT_EXPIRED: ODY0MDAwMDA=
  REDIS_HOST: cmVkaXMK
  REDIS_PORT: NjM3OQ==
  LOCAL_URL: aHR0cDovL2xvY2FsaG9zdDozMDAwLw==
  HEROKU_URL: aHR0cHM6Ly9zb2Z0c2VydmVkZW1vLmhlcm9rdWFwcC5jb20v
  BACKEND_URL: aHR0cHM6Ly9kZXZlbG9wLXNvZnRzZXJ2ZS5oZXJva3VhcHAuY29tLw==
  MAIL_USERNAME: ZW52LnVzZXJuYW1l
  MAIL_PASSWORD: ZW52LnBhc3N3b3Jk
  MONGO_DATABASE: c2NoZWR1bGVfbW9uZ28K   
  MONGO_SERVER: bW9uZ28K
  FACEBOOK_CLIENT_ID: NzQ4MzQyODUyMzgzNTQwCg==
  FACEBOOK_CLIENT_SECRET: N2VhY2MwMjcwNTZhYzJjYWNkZjNlZDQ1NjU5OGYzN2UK
  GOOGLE_CLIENT_ID: NTkzMTExNDU0NjgwLTUwMG5naTFuMmEwNTRnNDgwcmg4bmg1M2o0YjRsYjNhLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tCg==
  GOOGLE_CLIENT_SECRET: UVVwN1FTaDhGbWNpaXVBNmhqVDBFQnpWCg==
  TEST_LOCAL_URL: aHR0cDovL2xvY2FsaG9zdDozMDAwLwo=
  TEST_HEROKU_URL: aHR0cHM6Ly9zb2Z0c2VydmVkZW1vLmhlcm9rdWFwcC5jb20vCg==
  TEST_MAIL_USERNAME: bGFzdHZvdmExMjNAZ21haWwuY29tCg==
  TEST_MAIL_PASSWORD: c29mdHNlcnZlMQo=